package agent;

import transform.AccessEventSource;
import transform.CreationEventSource;

/**
 * A singleton redistributing events generated by instrumented client program.
 *
 * @author Marcin Szymczak <mpszymczak@gmail.com>
 */
public final class RuntimeEventSource {

    public static final RuntimeEventSource INSTANCE = new RuntimeEventSource();

    private CreationEventSource ces;
    private AccessEventSource aes;

    private RuntimeEventSource() {
        ces = new CreationEventSource();
        aes = new AccessEventSource();
    }

    public CreationEventSource getCreatEventSrc() {
        return ces;
    }

    public AccessEventSource getAccsEventSrc() {
        return aes;
    }
}
