package agent;

import transform.AccsEventSrc;
import transform.CreatEventSrc;

/**
 * A singleton taking the role of an event hub for events generated by
 * instrumented client program.
 *
 * @author Marcin Szymczak <mpszymczak@gmail.com>
 */
public final class RuntmEventSrc {

    public static final RuntmEventSrc INSTANCE = new RuntmEventSrc();

    private CreatEventSrc ces;
    private AccsEventSrc aes;

    private RuntmEventSrc() {
        ces = new CreatEventSrc();
        aes = new AccsEventSrc();
    }

    public CreatEventSrc getCreatEventSrc() {
        return ces;
    }

    public AccsEventSrc getAccsEventSrc() {
        return aes;
    }
}
